default:
    just --list

[working-directory: "build"]
cmake:
    cmake ..

[working-directory: "build"]
build: cmake
    bear --append -- make -j$(nproc --all)

run: build
    ./build/cpp_project

[working-directory: "build"]
clean:
    make clean -j$(nproc --all)

[working-directory: "build"]
distclean:
    -rm * .* -rf
